spring.application.name=eureka-server
server.port=8761
spring.profiles.active=dev

# === Config Server Settings ===
spring.config.import=optional:configserver:http://config-server:8888
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=eureka-server
eureka.instance.prefer-ip-address=true
