spring.application.name=eureka-server
server.port=8761

# === Config Server Settings ===
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.max-attempts=3
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.request-read-timeout=3000
spring.cloud.config.request-connect-timeout=3000

# === Eureka Self Registration ===
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# === Actuator Health ===
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
