sonar.projectKey=BranchPickingSystem
sonar.projectName=BranchPickingSystem
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=java
sonar.java.binaries=**/target/classes

sonar.host.url=http://localhost:9000
sonar.login=sqa_26fda6de3430b12177259408724d4793c1976918
