# =========================
# Spring Cloud Config Server
# =========================
spring.application.name=ConfigServerApp
server.port=8888

# =========================
# Git Backend (Config Repo)
# =========================
#spring.cloud.config.server.git.uri=file:///E:/BranchPickingSystem/ConfigRepo
# If using remote git repo (e.g., GitHub), replace with:
spring.cloud.config.server.git.uri=https://github.com/Harshardhan/ConfigRepo.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main

# =========================
# Eureka Client (Register Config Server to Eureka)
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

# =========================
# Logging
# =========================
logging.level.org.springframework.web=INFO
