spring.application.name=BranchPickingSystem
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

logging.file.name=./logs/app.log
logging.level.org.springframework.web=INFO
logging.pattern.file=%d{ISO8601} %-5level %logger{36} - %msg%n
