apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: master
  SPRING_DATASOURCE_PASSWORD: master
  SPRING_REDIS_PASSWORD: master
  EMAIL_USERNAME: harshavardhan.harish@gmail.com
  EMAIL_PASSWORD: iaxlmcodwbeeymqc
  SECURITY_JWT_SECRET: ThisIsASuperStrongSecretKeyWithAtLeast32Chars!