apiVersion: apps/v1
kind: Deployment
metadata:
  name: consolidation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consolidation-service
  template:
    metadata:
      labels:
        app: consolidation-service
    spec:
      containers:
        - name: consolidation-service
          image: consolidation-service:ci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
