apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-registration
  template:
    metadata:
      labels:
        app: user-registration
    spec:
      containers:
        - name: user-registration
          image: harsha79/user-registration:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8083

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
