spring.application.name=Common-Library

# Logging Configuration
logging.file.name=logs/common-library.log
logging.level.org.springframework.web=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
