name: CI - Build & Push Eureka

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: harsha79/eureka-server

jobs:
  build:
    runs-on: self-hosted

    outputs:
      sha: ${{ steps.get-sha.outputs.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build JAR
        shell: powershell
        run: mvn clean package -DskipTests

      - name: Docker Login
        shell: powershell
        run: |
          docker login -u "${env:DOCKERHUB_USERNAME}" -p "${env:DOCKERHUB_TOKEN}"

      - name: Get Commit SHA
        id: get-sha
        shell: powershell
        run: |
          $sha = git rev-parse --short HEAD
          Write-Host "Commit SHA: $sha"
          echo "::set-output name=sha::$sha"

      - name: Build & Push Docker Image
        shell: powershell
        run: |
          docker build -t "${env:IMAGE_NAME}:ci" -t "${env:IMAGE_NAME}:${{ steps.get-sha.outputs.sha }}" .
          docker push "${env:IMAGE_NAME}:ci"
          docker push "${env:IMAGE_NAME}:${{ steps.get-sha.outputs.sha }}"
