name: CI - Build & Push Eureka

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: harsha79/eureka-server

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Docker Login
        run: docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_TOKEN

      - name: Build & Push Image
        run: |
          if (-not $env:GITHUB_ACTIONS) { exit 1 }

          $SHA = $env:GITHUB_SHA.Substring(0,7)
          Write-Host "SHA=$SHA"

          docker build -t $env:IMAGE_NAME:$SHA .
          docker push $env:IMAGE_NAME:$SHA
