name: CD – Deploy Selected Services to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # you are using self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify kubectl access
      run: |
        kubectl version --client
        kubectl get nodes

    # -----------------------------
    # INFRA
    # -----------------------------
    - name: Deploy Redis
      run: kubectl apply -f k8s/infra/redis-deployment.yml

    - name: Deploy MySQL
      run: kubectl apply -f k8s/mysql/

    # -----------------------------
    # CONFIG & DISCOVERY
    # -----------------------------
    - name: Deploy Config Server
      run: |
        kubectl apply -f k8s/config-server.yml
        kubectl apply -f k8s/config-server-deployment.yml

    - name: Deploy Eureka Server
      run: |
        kubectl apply -f k8s/eureka-server.yml
        kubectl apply -f k8s/eureka-server-deployment.yml

    # -----------------------------
    # API GATEWAY
    # -----------------------------
    - name: Deploy API Gateway
      run: |
        kubectl apply -f k8s/api-gateway.yml
        kubectl apply -f k8s/api-gateway-deployment.yml

    # -----------------------------
    # BUSINESS SERVICES
    # -----------------------------
    - name: Deploy User Registration Service
      run: |
        kubectl apply -f k8s/user-registration.yml
        kubectl apply -f k8s/user-registration-deployment.yml

    - name: Deploy Product Service
      run: |
        kubectl apply -f k8s/product-service-application.yml
        kubectl apply -f k8s/product-service-application-deployment.yml
