spring.application.name=order-service
server.port=8081
spring.profiles.active=dev

eureka.client.service-url.defaultZone=http://98.89.123.106:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.config.import=optional:configserver:http://98.89.123.106:8888

spring.datasource.url=jdbc:mysql://database-1.ckda6oqeavac.us-east-1.rds.amazonaws.com:3306/orderdb
spring.datasource.username=admin
spring.datasource.password=Kasab#81
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
